/*
 * Copyright (c) 2026 by Naohide Sano, All rights reserved.
 *
 * Programmed by Naohide Sano
 */

package vavi.sound.opl3;

import javax.sound.sampled.AudioFormat;

import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.stream.Stream;
import java.util.zip.GZIPInputStream;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;


/**
 * Compares each player's OPL register-write stream against adplug's
 * reference dumps (test/testref/*.ref, generated by adplug's playertest
 * with the Testopl logger). A passing file means the java port produces
 * register-for-register identical output to adplug.
 * <p>
 * Reference format: {@code init}, {@code setchip(n)}, {@code reg <- val}
 * (hex) per register write, and {@code r%.2f} per successful update.
 * <p>
 * Normalization applied to both sides before comparison:
 * <ul>
 * <li>{@code init} / {@code setchip} lines are dropped (the java ports have
 * no chip-select notion; the chip is folded into the reg as
 * {@code (chip << 8) | reg})</li>
 * <li>regs and values are masked to 8 bits ({@code Testopl} logs raw ints,
 * e.g. {@code ffffffff} for -1, but every OPL emulator masks on write)</li>
 * <li>"init sweeps" are dropped: the java ports substitute
 * {@code opl->init()} (which logs nothing) with zero-writes to every
 * register in ascending order 0..ff</li>
 * </ul>
 *
 * @author <a href="mailto:umjammer@gmail.com">Naohide Sano</a> (nsano)
 * @version 0.00 2026-07-10 nsano initial version <br>
 */
public class AdplugRefTest {

    static final Path MUSIC_DIR = Path.of("src/test/resources/opl3");
    static final Path REF_DIR = Path.of("src/test/resources/opl3ref");

    /** hard cap on update() calls, in case a port loops forever */
    static final int MAX_UPDATES = 2_000_000;

    /**
     * Fixtures whose register streams are known to match adplug exactly.
     * Files of pre-existing players that have not been brought to
     * register-exactness yet (mid/cmf/laa/sci, herad, s3m, dmo, lds,
     * xsm, dro v1) are not listed.
     */
    static Stream<Arguments> refSamples() {
        return Stream.of(
                Arguments.arguments("2001.MKJ", "2001"),
                Arguments.arguments("AB_JULIA.A2T", "AB_JULIA"),
                Arguments.arguments("fank5.a2m", "fank5"),
                Arguments.arguments("fm-troni.a2m", "fm-troni"),
                Arguments.arguments("Flying.mdi", "Flying"),
                Arguments.arguments("RIK6.MDI", "RIK6"),
                Arguments.arguments("menu.got", "menu"),
                Arguments.arguments("opensong.got", "opensong"),
                Arguments.arguments("ACTION.PIS", "ACTION"),
                Arguments.arguments("ADAGIO.DFM", "ADAGIO"),
                Arguments.arguments("AKMTEC.MTR", "AKMTEC"),
                Arguments.arguments("ARAB.bam", "ARAB"),
                Arguments.arguments("BEGIN.KSM", "BEGIN"),
                Arguments.arguments("BOOTUP.M", "BOOTUP"),
                Arguments.arguments("CHIP.MTR", "CHIP"),
                Arguments.arguments("DEMO4.JBM", "DEMO4"),
                Arguments.arguments("DTM-TRK1.DTM", "DTM-TRK1"),
                Arguments.arguments("GALWAY.SOP", "GALWAY"),
                Arguments.arguments("HIP_D.ROL", "HIP_D"),
                Arguments.arguments("MARIO.A2M", "MARIO"),
                Arguments.arguments("REVELAT.SNG", "REVELAT"),
                Arguments.arguments("RI051.RIX", "RI051"),
                Arguments.arguments("SAILOR.CFF", "SAILOR"),
                Arguments.arguments("SATNIGHT.HSP", "SATNIGHT"),
                Arguments.arguments("SCALES.SA2", "SCALES"),
                Arguments.arguments("SONG1.sng", "SONG1"),
                Arguments.arguments("TOCCATA.MAD", "TOCCATA"),
                Arguments.arguments("TU_BLESS.AMD", "TU_BLESS"),
                Arguments.arguments("WONDERIN.WLF", "WONDERIN"),
                Arguments.arguments("alloyrun.rad", "ALLOYRUN"),
                Arguments.arguments("blaster2.msc", "blaster2"),
                Arguments.arguments("bmf1_1.bmf", "bmf1_1"),
                Arguments.arguments("bmf1_2.xad", "bmf1_2"),
                Arguments.arguments("crusader.raw", "crusader"),
                Arguments.arguments("dro_v2.dro", "dro_v2"),
                Arguments.arguments("dune19.adl", "DUNE19"),
                Arguments.arguments("dystopia.rad", "dystopia"),
                Arguments.arguments("ending.sop", "ending"),
                Arguments.arguments("eobsound.adl", "EOBSOUND"),
                Arguments.arguments("flash.xad", "flash"),
                Arguments.arguments("go-_-go.ims", "go-_-go"),
                Arguments.arguments("hybrid.xad", "hybrid"),
                Arguments.arguments("hyp.xad", "hyp"),
                Arguments.arguments("inc.raw", "inc"),
                Arguments.arguments("lines1.mus", "lines1"),
                Arguments.arguments("logical.plx", "logical"),
                Arguments.arguments("playmus1.sng", "PLAYMUS1"),
                Arguments.arguments("psi1.xad", "psi1"),
                Arguments.arguments("rat.xad", "rat"),
                Arguments.arguments("revival.ims", "revival"),
                Arguments.arguments("smkerem.hsc", "SMKEREM"),
                Arguments.arguments("tafa.mus", "tafa"),
                Arguments.arguments("thealibi.d00", "TheAlibi"),
                Arguments.arguments("vib_vol3.d00", "VIB_VOL3"),
                Arguments.arguments("well.adl", "well")
        );
    }

    @ParameterizedTest
    @MethodSource("refSamples")
    @DisplayName("register stream matches adplug reference dump")
    void refCompare(String music, String ref) throws Exception {
        Path path = MUSIC_DIR.resolve(music);
        List<String> actual = normalize(dump(path));
        List<String> expected = normalize(readRef(REF_DIR.resolve(ref + ".ref.gz")));

        int n = Math.min(actual.size(), expected.size());
        for (int i = 0; i < n; i++) {
            if (!expected.get(i).equals(actual.get(i))) {
                assertEquals(expected.get(i), actual.get(i),
                        music + ": register stream diverges from adplug at line " + i + " of " + n);
            }
        }
        assertEquals(expected.size(), actual.size(), music + ": register stream length");
    }

    /** plays the file, capturing all register writes in ref format */
    static List<String> dump(Path path) throws IOException {
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        try (InputStream is = new BufferedInputStream(Files.newInputStream(path));
             PrintStream ps = new PrintStream(bos, false, StandardCharsets.US_ASCII)) {

            AudioFormat.Encoding encoding = Opl3Player.getEncoding(is);
            assertTrue(encoding != null, path + ": no player detected");
            Opl3Player player = Opl3Player.getPlayer(encoding);
            player.setProperties(Map.of("uri", path.toUri()));

            Opl3Player.regLog = ps;
            try {
                player.load(is);

                int updates = 0;
                while (player.update() && updates++ < MAX_UPDATES) {
                    ps.printf(Locale.ROOT, "r%.2f%n", player.getRefresh());
                }
            } finally {
                Opl3Player.regLog = null;
            }
        }
        return bos.toString(StandardCharsets.US_ASCII).lines().toList();
    }

    static List<String> readRef(Path refGz) throws IOException {
        try (BufferedReader r = new BufferedReader(new InputStreamReader(
                new GZIPInputStream(Files.newInputStream(refGz)), StandardCharsets.US_ASCII))) {
            return r.lines().toList();
        }
    }

    static List<String> normalize(List<String> lines) {
        List<String> masked = new ArrayList<>(lines.size());
        for (String l : lines) {
            l = l.trim();
            if (l.isEmpty() || l.equals("init") || l.startsWith("setchip")) {
                continue;
            }
            int sep = l.indexOf(" <- ");
            if (sep >= 0) {
                try {
                    long reg = Long.parseLong(l.substring(0, sep), 16);
                    long val = Long.parseLong(l.substring(sep + 4), 16);
                    l = Long.toHexString(reg & 0xff) + " <- " + Long.toHexString(val & 0xff);
                } catch (NumberFormatException ignored) {
                }
            }
            masked.add(l);
        }

        // drop init sweeps (see class javadoc)
        List<String> out = new ArrayList<>(masked.size());
        int i = 0;
        int n = masked.size();
        while (i < n) {
            if (masked.get(i).equals("0 <- 0")) {
                int last = -1;
                int k = i;
                while (k < n && masked.get(k).endsWith(" <- 0")) {
                    int reg = Integer.parseInt(masked.get(k).substring(0, masked.get(k).indexOf(' ')), 16);
                    if (reg == last || reg == last + 1) {
                        last = reg;
                        k++;
                    } else {
                        break;
                    }
                }
                if (last == 0xff) {
                    i = k; // drop the sweep
                    continue;
                }
            }
            out.add(masked.get(i));
            i++;
        }
        return out;
    }
}
